### ISSUE TITLE
Select Hifiberry Digi+ as output results in crash

### ISSUE THREAD

**Issue by andsens** [osmc/osmc#196]
After changing to stable, I am unable to select my Hifiberry Digi+ board as an output device. The entire system crashes (ssh unresponsive as well). I am running OSMC stable on a Raspberry Pi 2 (I selected the hifiberry digi overlay in osmc settings).

**Comment by samnazarko** [comment]
Did you disable Enable GPIO LIRC remote support first?

**Comment by andsens** [comment]
... I did not. It works now! Thanks!  
You word your answer like I should have known this. Was there a guide I should have read but missed?

**Comment by samnazarko** [comment]
Closed as invalid

We will make sure they do not conflict in the future.

**Comment by szczukot** [comment]
Why this is closed ?
I want use OSMC with HIFIBerry and LIRC :(
When i enable LIRC and set HIFIBerry (without GPIO pin conflict) i have crashed.

Fantom

**Comment by DBMandrake** [comment]
This issue is related to the My OSMC Pi Config module not automatically disabling LIRC GPIO support when enabling HiFiBerry on the same GPIO pins. That has been fixed.

If you are having problems with a crash when using both HiFiBerry and LIRC GPIO on different GPIO pins please start a new support thread at http://discourse.osmc.tv with full debug logs.

**Comment by samnazarko** [comment]
We allow you to change the pins in My OSMC so they are non conflicting.
