### ISSUE TITLE
JSON-RPC Files.GetSources returns nothing because sources.xml is not generated

### ISSUE THREAD

**Issue by piengeng** [osmc/osmc#208]
Hi Sam, I'm facing an issue with json-rpc only happened on osmc, I'd posted a bug (turns out it's not a kodi bug) on http://forum.kodi.tv/showthread.php?tid=235063. I'm not sure if osmc is using a modified kodi or not. Could you please help?

**Comment by piengeng** [comment]
The OSMC I'm updating from I believe should be RC3, if not mistaken. I'm not sure if this is the same case with latest release, I'd already updated to latest OSMC via apt-get. ~/kodi/userdata/sources.xml still doesn't generated automically. Instead, I've to create one myself as suggested in kodi's forum. 

It's just weird for me because sources.xml seems automatically generated on windows 8.1. 

It would help other users to use Missing Movie Scanner plugin properly if this could fixed. Maybe I'm the only one facing this issue. Anyway, please let me know if you wish to close this issue. Thanks for OSMC :+1:

**Comment by DBMandrake** [comment]
Not a bug, but normal Kodi behaviour.

I think Millhouse explains the situation well in the Kodi thread - sources.xml is only ever created by YOU when you add video sources via the GUI.

**Comment by piengeng** [comment]
The issue remains, I did add the video sources through Kodi's GUI.

**Comment by DBMandrake** [comment]
If sources.xml was not populated with data when you add a video source then next time you load Kodi the sources under Video -> Files would be gone again, because this is where the sources are read from by the GUI...

(Separate to the sources for library entries which are stored independently in the database)

Nobody else has reported this issue before and it is not a general bug in OSMC, rather something peculiar to your installation that needs troubleshooting. 

Therefore please create a new support thread on http://discourse.osmc.tv with full debug logs taken after adding some video sources.
