### ISSUE TITLE
RPi2: Library gone after reboot during first library scrape

### ISSUE THREAD

**Issue by fcjversc** [osmc/osmc#223]
Steps to reproduce:
1. New install OSMC August
2. Add video source (e.g. Movies), start scraping
3. Notice menu item Movies is added during scrape
4. During scrape, pull the power plug and replug/reboot
5. Notice that library/menu item is gone
6. Manual refresh is not working.

Hi,

I've reinstalled my OSMC installation twice to verify whether this is really an issue with OSMC. I noticed that when you pull the power plug during the first scrape, the "Movie" or "Series" library is gone and cannot be refreshed (not even manually). This happened because i plug the USB power supply in my TV, so the RPI2 is powered on when my TV is powered on, and powered off when i power off my tv. 

During the first scrape, i noticed the "Movie" menu item is displayed on the homescreen. If i turn off the tv during the scrape, removing the power source, the "Movie" menu item is removed after the next restart. The movie folder is only visible if you go to Video - Files. If i manually press refresh in the files folder, nothing happens.

**Comment by ActionAdam** [comment]
Powering by TV USB is never recommended for this reason among others.  Kodi is never intended to be crashed (forcibly) while writing a library db. ~/.kodi/userdata/Database/MyVideos93.db corruption due to power loss is likely what's resulting in the failure to recover the db on subsequent boots.  This is not a software bug exclusive to OSMC but an expected likely result when virtually any linux system is not shutdown cleanly as a result of power loss while writing files.

**Comment by DBMandrake** [comment]
Pulling the power out in the middle of a database import corrupting the database is a not a bug.

Don't power your device from a TV and don't pull out the power during a database scan/import.
