### ISSUE TITLE
WAN buffering troubles

### ISSUE THREAD

**Issue by KZL92** [osmc/osmc#306]
Hello,

I download my movies though SSH using filezilla.

I can read the movie from the beginning when it is downloading. 
But I can't fast forward in the part of the film which is downloaded..

Actually I notice that I can forward sometime, but some other time I can't.

I think that I have a buffer issue when I try to buffer data currently coming from the web.

**Comment by samnazarko** [comment]
If you're trying to play back content that is not transferred completely, then seeking will likely not work properly.

Start a forum post if this is not the case and you believe you have encountered a bug

**Comment by DBMandrake** [comment]
Some non-streaming file container formats cannot be played if the file is incomplete because some metadata is located at the end of the file. (AVI is one such example) So this is unlikely to be a bug, and you are just trying to do something that can't be done.

On the other hand transport streams are specifically designed to be able to play while streaming as the data and metadata is positioned in the file and interleaved in a way that does not require forward lookups later in the file (for example metadata) to play earlier content.

**Comment by KZL92** [comment]
I have to say that I know this issue with AVI files and it's basically normal with AVI or MP4.

Here it's a MKV file and as I said I can seek into the movie, but it takes upto 5-10 minutes to reach the 50th minute of the movie.
It's definitely not a problem of file since I can seek and read my MKV from my laptop directly using kodi. 
The problem occurs only when I'm using OSMC with a raspberry pi, that's why I suspect a buffer issue/bad configuration.

**Comment by DBMandrake** [comment]
So you are trying to copy the file from a Windows PC to OSMC using FileZilla (SFTP) and play it at the same time that it is copying ? As said, that is not going to work properly.

Why don't you just share the file and stream it via NFS or SMB ?

**Comment by KZL92** [comment]
Precisely I copy the file from a NAS server (located at my parent's house though SSH) to a computer which broadcast a SMB server to OSMC.
I already try to directly connect a NFS sharing directly from my parent's house, but it's worst than the current solution.

I mean there is no trouble about my configuration with 3 different laptops when I download the movie and I play it back directly. I can seek without trouble. Only with OSMC and the raspberry pi it's seem to have this playback issue when I seek into my file. Maybe there is something to do with the advancedsetting.xml file ?

**Comment by KZL92** [comment]
I already try different configurations of advancedsetting by I came back to the default one.

**Comment by samnazarko** [comment]
Until this is confirmed to be an issue with OSMC this is not the place.

Start a forum post with a description of your issue as well as a debug log

**Comment by KZL92** [comment]
I don't get it, it's not a issue section ? Well it should not be dilute in a forum post..
Where it is there is an official one ? Can I have a link ?

**Comment by samnazarko** [comment]
This place is for confirmed bug reports.

The forum can be found at discourse.osmc.tv.

You have neither provided the necessary information to investigate the issue (if it is an issue rather than a limitation) nor posted in the proper channel. To receive the best support and chance of resolution, please see our forum.

**Comment by KZL92** [comment]
Well thank you!
I will copy/paste my post.

I asked, just because I don't know which detail to give. Just ask me more details..

**Comment by samnazarko** [comment]
All of this is covered via osmc.tv. In particular, you want: https://osmc.tv/wiki/general/how-to-submit-a-useful-support-request/.

Did you install OSMC via NOOBS? I'm curious how you have managed to download OSMC but missed some vital resources. If you can let us know where you grabbed OSMC from we can improve the visibility of help and community.
