### ISSUE TITLE
Missing libupnp6 in standard Raspberry Pi 2 build

### ISSUE THREAD

**Issue by jonnyosmer** [osmc/osmc#344]
Hello,
Thanks for the great package, a little issue I hit:
I've installed the standard OSMC RPi 2 image (OSMC_TGT_rbp2_20161224) and it wasn't seeing my UPNP/DLNA server (mediatomb). I did sudo apt-get install libupnp6 and it worked from there. I don't think there is a GUI menu option to do this.
Please add libupnp6 to the default package list.

Regards,
Jonny

**Comment by samnazarko** [comment]
We have a lot of people using Kodi's DLNA capabilities, but this is the first report that we have had suggesting that we are missing a library.

If there is a dependency on this library, it is dyloaded instead of being linked at build time or Kodi would not run at all. This should generate a Kodi error message if this is the case. Can you remove libupnp6 and reproduce the problem with debug logging enabled?

I believe that Kodi builds its own UPNP libraries and statically links against it, as libupnp6 is not listed as a dependency in the official compilation instructions for Kodi: https://github.com/xbmc/xbmc/blob/master/docs/README.linux.
