### ISSUE TITLE
Slow Wifi speed with internal and external Wifi on RPi 3

### ISSUE THREAD

**Issue by theincogtion** [osmc/osmc#347]
I had problems to stream my movies from my NAS and discovered low wifi speeds.
I mounted the smb share directly to my RPi 3 and started copying files. Maximum speed is 15Mbit/s. Which explains my problems to stream movies. 

- I placed the RPi 3 besides my router to see if this changes the wifi speed -> it did not had any affect.
- I took an usb wireless card to see if this performs better -> it doesn't
- I used wget to make some speedtests to the internet -> same speed issue

My log:
http://paste.osmc.io/sudehukado

I also posted this issue in osmc forum:
https://discourse.osmc.tv/t/wifi-vs-wired-performance-huge-difference/21253/9?u=theincogtion

Router is
ASUS RT-AC66U

Linux is
Linux osmcwohn 4.4.27-5-osmc #1 SMP PREEMPT Tue Nov 22 02:23:12 UTC 2016 armv7l GNU/Linux

**Comment by samnazarko** [comment]
The bug tracker is for confirmed issues only.

**Comment by saperlot** [comment]
@samnazarko i also do see a speed issue on my rpi 2 since the 17 release. I never had buffering issues with 16.

**Comment by samnazarko** [comment]
Start a forum post with debug logs

Sent from a mobile device, so please excuse the brevity of this reply

On 8 May 2017, at 19:53, saperlot <notifications@github.com<mailto:notifications@github.com>> wrote:


@samnazarko<https://github.com/samnazarko> i also do see a speed issue on my rpi 2 since the 17 release. I never had buffering issues with 16.

-
