### ISSUE TITLE
Adding apt key fails when building image on stretch

### ISSUE THREAD

**Issue by Sjord** [osmc/osmc#396]
I am trying to build a stretch OSMC image. In osmc-rbp2-filesystem/build.sh I changed jessie to stretch.

The install then fails because the key is not properly loaded:
```
Adding apt key
--2017-09-07 19:51:03--  http://apt.osmc.tv/apt.key
Resolving apt.osmc.tv (apt.osmc.tv)... 159.253.212.250
Connecting to apt.osmc.tv (apt.osmc.tv)|159.253.212.250|:80... connected.
HTTP request sent, awaiting response... 302 Found
Location: http://ftp.fau.de/osmc/osmc/apt/apt.key [following]
--2017-09-07 19:51:03--  http://ftp.fau.de/osmc/osmc/apt/apt.key
Resolving ftp.fau.de (ftp.fau.de)... 131.188.12.211, 2001:638:a000:1021:21::1
Connecting to ftp.fau.de (ftp.fau.de)|131.188.12.211|:80... connected.
HTTP request sent, awaiting response... 200 OK
Length: 1727 (1.7K) [application/pgp-keys]
Saving to: ‘osmc-rbp2-filesystem//tmp/key’

osmc-rbp2-filesystem//tmp/ 100%[========================================>]   1.69K  --.-KB/s    in 0s      

2017-09-07 19:51:03 (203 MB/s) - ‘osmc-rbp2-filesystem//tmp/key’ saved [1727/1727]

E: gnupg, gnupg2 and gnupg1 do not seem to be installed, but one of them is required for this operation
Updating sources
Ign:2 http://ftp.debian.org/debian stretch InRelease
...                        
Get:19 http://ftp.debian.org/debian stretch/non-free Translation-en [79.2 kB]                              
Fetched 13.1 MB in 24s (538 kB/s)                                                                          
Reading package lists... Done
W: GPG error: http://ftp.fau.de/osmc/osmc/apt stretch InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 553B25A766C762CC
W: The repository 'http://apt.osmc.tv stretch InRelease' is not signed.
N: Data from such a repository can't be authenticated and is therefore potentially dangerous to use.
N: See apt-secure(8) manpage for repository creation and user configuration details.
Installing core packages
Reading package lists... Done
Building dependency tree... Done
E: Unable to locate package rbp-userland-osmc
Exiting build
```

A workaround is to install gnupg when doing the debootstrap:

```
fetch_filesystem "--no-check-gpg --arch=${ARCH} --foreign --include=gnupg --variant=minbase ${RLS} ${DIR} ${URL}"
```

I am not sure whether this is the correct solution. But with this adding the key works correctly, and the building exits with the following error:
```
E: Unable to locate package rbp-userland-osmc
```

**Comment by samnazarko** [comment]
The Stretch repository hasn't been fully built yet, so building an image will not succeed.

I will rework the apt-key method soon. It's on my notes but I thought I had resolved it before.

**Comment by samnazarko** [comment]
Hi @Sjord 

I've looked in to this. With Debian Stretch, gnupg is no longer a dependency of minbase Stretch. It is now a recommended package by apt-key instead of an explicit dependency. Not installing this package seems to save us about 40MB.

Raspbian brings this in automatically because raspbian-archive-keyring depends on these packages.
For ARMv7, AMD64 and Aarch64, which don't use Raspbian repositories.

I've chosen to add our key directly to trusted.gpg.d, as recommended by Debian [1]:

>Note: Instead of using this command a keyring should be placed directly in the /etc/apt/trusted.gpg.d/ directory with a descriptive name and either "gpg" or "asc" as file extension.

Other projects, such as Docker, are also following suit [2]: 

It looks like the Raspberry Pi repository itself is doing the same [3], but Raspbian haven't changed yet.

For the OSMC key, we now import this via the recommended method.

[1] https://manpages.debian.org/stretch/apt/apt-key.8.en.html
[2] https://github.com/docker-library/mysql/pull/254/commits/b4b7c8eea0690d0406a5ffc2d3404c8c42457a2d
[3]  https://github.com/RPi-Distro/repo/issues/59

**Comment by Sjord** [comment]
Thanks for the elaborate explanation, @samnazarko!
