### ISSUE TITLE
Network Error on Setup

### ISSUE THREAD

**Issue by mark5four0** [osmc/osmc#507]
Getting an network error when setting up the OSMC in 4/2019 release. It wouldn't set up network and would get stuck in network setup menu. If I skipped that menu, it would boot to kodi, but network wouldn't install. (even on command line with connmanctl)

it said check logs, but nothing was logged to kodi log. 

fixed by removing targus bluetooth and logitech keyboard dongle and reinstalling.

**Comment by samnazarko** [comment]
What device are you using?

On 8 May 2019, at 17:37, mark5four0 <notifications@github.com<mailto:notifications@github.com>> wrote:


Getting an network error when setting up the OSMC in 4/2019 release. It wouldn't set up network and would get stuck in network setup menu. If I skipped that menu, it would boot to kodi, but network wouldn't install. (even on command line with connmanctl)

it said check logs, but nothing was logged to kodi log.

fixed by removing targus bluetooth and logitech keyboard dongle and reinstalling.

**Comment by samnazarko** [comment]
Please start a forum post so we can look in to this further.
