### ISSUE TITLE
Wifi not working...

### ISSUE THREAD

**Issue by ghost** [osmc/osmc#54]
Installer : http://osmc.tv/download/linux/
Version : OSMC ALPHA2
Hardware : Raspberry Pi B+ with rtl8192cu

Followed the prompts and entered the SSID and key 
On boot there is no IP address (would help if there was a OpenELEC style interface for networking) 

I'm setting up a wired LAN to investigate and collect logs.
Any tips would be appreciated.. :)

**Comment by pehota** [comment]
Hi,
I have the same same hardware configuration as alanrburns and am using Alpha 3.
Wi-fi isn't working for me.
Tried Alpha 2 (just in case) - still no wi-fi.

Installer : https://osmc.tv/download/windows
Version : OSMC ALPHA3
Hardware : Raspberry Pi B+ with rtl8192cu

Thanks

**Comment by HenrikNyberg** [comment]
I have the same problem with Alpha 4.

**Comment by ciptok** [comment]
I had the same problem with rtl8192cu based dongle on Alpha4. The issue was related to wrongly configured connman settings for picked wifi network (var/lib/connman/). I believe this is created by OSMC installer. In my case network identifier was different than the one shown by connman service.

Workaround:
1) Connect to RPi through cable by ssh (login: osmc, pass: osmc)
2) Run commands:

 $ connmanctl
connmanctl> scan wifi
connmanctl> services   (you'll see list of available networks)
connmanctl> agent on
connmanctl> connect wifi_111111111111_2222222222_managed_psk   (pick your network)

Agent will ask you for network details. Once finish you should be automatically connected to network. Settings will be saved thus no need for redoing it after.

**Comment by samnazarko** [comment]
Can you explain what you mean by 

"The issue was related to wrongly configured connman settings for picked wifi network (var/lib/connman/). I believe this is created by OSMC installer."

Is there something that needs fixing on our side?

**Comment by ciptok** [comment]
Configuration I had in /var/lib/connman/ was defined for network ID wifi_30144a1a9989_4254487562332d545a4d37_managed_psk whereas the one that is shown by connmanctl tool is wifi_30144a1a9989_4254487562332d545a4d37_managed_psk.

I'm not expert of connman tool and not sure where this difference come from. I'm wondering when initial configuration was created. Is it done by OSMC installer or initialized over the first startup?

Pls note in my case first established wifi connection was done using different dongle - not sure if it matters here. I hope that explains clearer the problem to you. I'll also try to reproduce the problem again and dig more about main cause.

**Comment by HenrikNyberg** [comment]
I found the same solution as you did! So I did the connection in terminal and it worked, at least for a while, now it goes on and off. Still get a error in dmesg saying it can't load firmware. When setting up the system I used the installer and entered the right ssid (have no spaces) and passkey. Now when I search for networks in the gui, it will not show me any networks. When I ping the unit from a nother system I can se how long time it's on and off, lets say it's down for about 30 min and then it's on for about 1-2 minutes.
