### ISSUE TITLE
Kodi sporadically freezes during media playback

### ISSUE THREAD

**Issue by mvglasow** [osmc/osmc#545]
### Steps to reproduce

1. Play media (playlist of several MP3s)
2. Wait

### Expected behavior

Kodi plays media and advances to the next item in the playlist after the current one finishes playing.

### Actual behavior

Occasionally Kodi freezes during media playback. This time, Kodi played the current track until the end and then stopped (despite more items being in the playlist). When I checked the screen (I was in player mode at the time), I saw the UI had frozen roughly 2/3 into the track.

### Environment

* Raspberry Pi 3, updated to the latest version today. The system was installed with the November 2019 release just a few days ago; today was the first update.
* The device is hooked up to a TV via HDMI; I use the TV remote via CEC to control it.
* All media files reside on a Samba server and are accessed via SMB. (Network is WiFi; the access point is right next to the Pi and plugged into my home LAN. The file server is another Pi with an external HD, running Raspbian, on a wired LAN connection.)
* The Pi is on an AC adaptor specifically sold for use with the Pi, and not overclocked.

### Additional information

This has occurred sporadically before the update, hence the Nov2019 release is affected as well. If I remember correctly, in at least some of the earlier occurrences playback stopped abruptly before the end of the current track. I can’t tell for sure if this happened only during media playback, or how different types of media affect behavior.

Every time I tried to SSH into the device, I was able to log in and issue `sudo init 6` on the shell to reboot the device. It seems to be only Kodi (and apparently only certain parts of it) which freezes.

I am currently not using Kore, thus I cannot tell if the remote still responds when the UI freezes. I also have not tried a USB keyboard.

Let me know if you need any additional information; I will collect what I can as soon as I re-encounter this issue.

**Comment by samnazarko** [comment]
Please open a support request on the forums. This section is for confirmed issues only.

On 4 Feb 2020, at 21:13, mvglasow <notifications@github.com> wrote:

﻿
Steps to reproduce

  1.  Play media (playlist of several MP3s)
  2.  Wait

Expected behavior

Kodi plays media and advances to the next item in the playlist after the current one finishes playing.

Actual behavior

Occasionally Kodi freezes during media playback. This time, Kodi played the current track until the end and then stopped (despite more items being in the playlist). When I checked the screen (I was in player mode at the time), I saw the UI had frozen roughly 2/3 into the track.

Environment

  *   Raspberry Pi 3, updated to the latest version today. The system was installed with the November 2019 release just a few days ago; today was the first update.
  *   The device is hooked up to a TV via HDMI; I use the TV remote via CEC to control it.
  *   All media files reside on a Samba server and are accessed via SMB. (Network is WiFi; the access point is right next to the Pi and plugged into my home LAN. The file server is another Pi with an external HD, running Raspbian, on a wired LAN connection.)
  *   The Pi is on an AC adaptor specifically sold for use with the Pi, and not overclocked.

Additional information

This has occurred sporadically before the update, hence the Nov2019 release is affected as well. If I remember correctly, in at least some of the earlier occurrences playback stopped abruptly before the end of the current track. I can’t tell for sure if this happened only during media playback, or how different types of media affect behavior.

Every time I tried to SSH into the device, I was able to log in and issue sudo init 6 on the shell to reboot the device. It seems to be only Kodi (and apparently only certain parts of it) which freezes.

I am currently not using Kore, thus I cannot tell if the remote still responds when the UI freezes. I also have not tried a USB keyboard.

Let me know if you need any additional information; I will collect what I can as soon as I re-encounter this issue.
