### ISSUE TITLE
October update broke something? 

### ISSUE THREAD

**Issue by develroo** [osmc/osmc#575]
Ok so updated the box with apt full-upgrade had to do that twice to get up to buster but now mediacenter crashes because of a mis matched API?

```
Oct 21 09:04:23 Vero4k mediacenter[2492]: ERROR in Mali driver:
Oct 21 09:04:23 Vero4k mediacenter[2492]:  * Device driver API mismatch
Oct 21 09:04:23 Vero4k mediacenter[2492]:  * Device driver API version: 900
Oct 21 09:04:23 Vero4k mediacenter[2492]:  * User space API version: 800

```

It is a Vero4K+ box 

```
uname -a 
Linux Vero4k 4.9.113-18-osmc #1 SMP PREEMPT Fri May 1 05:00:53 UTC 2020 aarch64 GNU/Linux

```
```

dpkg -l |grep osmc
ii  armv7-bluez-osmc                      5.43-4                              armhf        bluez for OSMC
ii  armv7-connman-osmc                    1.3.6-3                             armhf        connman for OSMC
ii  armv7-diskmount-osmc                  1.5.7                               armhf        Disk automounting for OSMC using udisks with standby support
ii  armv7-eventlircd-osmc                 1.4.5                               armhf        eventlircd for OSMC
rc  armv7-libass-osmc                     0.13.6                              armhf        libass library
ii  armv7-libbluray-osmc                  1.2.0-3                             armhf        libbluray library for OSMC
rc  armv7-libnfs-osmc                     1.10.0-2                            armhf        libnfs library
ii  armv7-librtmp-osmc                    2.4.0-11                            armhf        librtmp library
ii  armv7-libshairplay-osmc               0.1.8                               armhf        libshairplay package
ii  armv7-libsqlite-osmc                  3.28.0-2                            armhf        libsqlite optimised for Kodi
ii  armv7-lirc-osmc                       0.9.4-5                             armhf        lirc for osmc
ii  armv7-network-osmc                    1.7.9                               armhf        Network support for OSMC
ii  armv7-remote-osmc                     1.2.3                               armhf        Remote support for OSMC, achieved with lirc and eventlircd
ii  armv7-splash-osmc                     1.3.7                               armhf        Splash screen implementation for OSMC using ply-lite
ii  armv7-udisks-glue-osmc                1.3.5-11                            armhf        udisks for OSMC
ii  armv7-udisks-osmc                     1.0.5-12                            armhf        udisks for OSMC
ii  base-files-osmc                       2.9.6                               all          modified base-files for OSMC system
ii  libamcodec-osmc                       1.5.0-4                             armhf        libamcodec
ii  mediacenter-addon-osmc                3.0.689                             all          OSMC addon for mediacenter
ii  mediacenter-eventclients-common-osmc  1.0.3                               all          Eventclient common resources for mediacenter
ii  mediacenter-send-osmc                 1.0.0-5                             all          Eventclient send for mediacenter
ii  mediacenter-skin-osmc                 18.4.0-51                           all          OSMC skin for mediacenter
ii  niceprioritypolicy-osmc               1.0.3                               all          Configures /etc/security/limits.d to allow NICE value to be changed
ii  perftune-osmc                         1.2.8                               all          Performance tuning tweaks for OSMC
ii  ssh-app-osmc                          1.2.4                               all          SSH server for OSMC with prepopulated configuration
ii  vero3-bootloader-osmc                 1.5.0-1                             armhf        Vero 4K/4K+ UBoot package
ii  vero3-device-osmc                     1.4.8                               armhf        Vero 3 metapackage
ii  vero3-earlysplash-osmc                1.0.4                               armhf        Vero3 logo partition
ii  vero3-ftr-osmc                        1.5.7                               armhf        First-time-run scripts for OSMC
ii  vero3-fwenv-osmc                      2016.01-4                           armhf        firmware tools for OSMC
ii  vero3-libamcodec-osmc                 1.3.0-2                             armhf        libamcodec
ii  vero3-libcec-osmc                     4.0.4-5                             armhf        libcec
ii  vero3-mediacenter-osmc                18.8.0-3                            armhf        Media Center package for OSMC
ii  vero3-userland-osmc                   1.8.7                               armhf        Vero 3 userland package
ii  vero3-wifi-osmc                       1.3.0-1                             armhf        Broadcom patchram implementation for Vero
ii  vero364-headers-4.9.113-18-osmc:arm64 18                                  arm64        Header files related to Linux kernel, specifically,
ii  vero364-image-4.9.113-18-osmc:arm64   18                                  arm64        Linux kernel binary image for version 4.9.113-18-osmc
ii  vero364-kernel-osmc:arm64             3.9.173                             arm64        Kernel meta package bringing in the latest OSMC kernel for this device
ii  wireless-firmware-osmc                1.1.5                               all          Wireless firmware (proprietary) for OSMC

```

So seeing as the video driver is built into the kernel how did they get mismatched ? 

Thoughts ?

**Comment by samnazarko** [comment]
You probably didn’t add the new 4.9 repository.


On 21 Oct 2020, at 14:26, develroo <notifications@github.com> wrote:

﻿

Ok so updated the box with apt full-upgrade had to do that twice to get up to buster but now mediacenter crashes because of a mis matched API?

Oct 21 09:04:23 Vero4k mediacenter[2492]: ERROR in Mali driver:
Oct 21 09:04:23 Vero4k mediacenter[2492]:  * Device driver API mismatch
Oct 21 09:04:23 Vero4k mediacenter[2492]:  * Device driver API version: 900
Oct 21 09:04:23 Vero4k mediacenter[2492]:  * User space API version: 800



It is a Vero4K+ box

uname -a
Linux Vero4k 4.9.113-18-osmc #1 SMP PREEMPT Fri May 1 05:00:53 UTC 2020 aarch64 GNU/Linux




dpkg -l |grep osmc
ii  armv7-bluez-osmc                      5.43-4                              armhf        bluez for OSMC
ii  armv7-connman-osmc                    1.3.6-3                             armhf        connman for OSMC
ii  armv7-diskmount-osmc                  1.5.7                               armhf        Disk automounting for OSMC using udisks with standby support
ii  armv7-eventlircd-osmc                 1.4.5                               armhf        eventlircd for OSMC
rc  armv7-libass-osmc                     0.13.6                              armhf        libass library
ii  armv7-libbluray-osmc                  1.2.0-3                             armhf        libbluray library for OSMC
rc  armv7-libnfs-osmc                     1.10.0-2                            armhf        libnfs library
ii  armv7-librtmp-osmc                    2.4.0-11                            armhf        librtmp library
ii  armv7-libshairplay-osmc               0.1.8                               armhf        libshairplay package
ii  armv7-libsqlite-osmc                  3.28.0-2                            armhf        libsqlite optimised for Kodi
ii  armv7-lirc-osmc                       0.9.4-5                             armhf        lirc for osmc
ii  armv7-network-osmc                    1.7.9                               armhf        Network support for OSMC
ii  armv7-remote-osmc                     1.2.3                               armhf        Remote support for OSMC, achieved with lirc and eventlircd
ii  armv7-splash-osmc                     1.3.7                               armhf        Splash screen implementation for OSMC using ply-lite
ii  armv7-udisks-glue-osmc                1.3.5-11                            armhf        udisks for OSMC
ii  armv7-udisks-osmc                     1.0.5-12                            armhf        udisks for OSMC
ii  base-files-osmc                       2.9.6                               all          modified base-files for OSMC system
ii  libamcodec-osmc                       1.5.0-4                             armhf        libamcodec
ii  mediacenter-addon-osmc                3.0.689                             all          OSMC addon for mediacenter
ii  mediacenter-eventclients-common-osmc  1.0.3                               all          Eventclient common resources for mediacenter
ii  mediacenter-send-osmc                 1.0.0-5                             all          Eventclient send for mediacenter
ii  mediacenter-skin-osmc                 18.4.0-51                           all          OSMC skin for mediacenter
ii  niceprioritypolicy-osmc               1.0.3                               all          Configures /etc/security/limits.d to allow NICE value to be changed
ii  perftune-osmc                         1.2.8                               all          Performance tuning tweaks for OSMC
ii  ssh-app-osmc                          1.2.4                               all          SSH server for OSMC with prepopulated configuration
ii  vero3-bootloader-osmc                 1.5.0-1                             armhf        Vero 4K/4K+ UBoot package
ii  vero3-device-osmc                     1.4.8                               armhf        Vero 3 metapackage
ii  vero3-earlysplash-osmc                1.0.4                               armhf        Vero3 logo partition
ii  vero3-ftr-osmc                        1.5.7                               armhf        First-time-run scripts for OSMC
ii  vero3-fwenv-osmc                      2016.01-4                           armhf        firmware tools for OSMC
ii  vero3-libamcodec-osmc                 1.3.0-2                             armhf        libamcodec
ii  vero3-libcec-osmc                     4.0.4-5                             armhf        libcec
ii  vero3-mediacenter-osmc                18.8.0-3                            armhf        Media Center package for OSMC
ii  vero3-userland-osmc                   1.8.7                               armhf        Vero 3 userland package
ii  vero3-wifi-osmc                       1.3.0-1                             armhf        Broadcom patchram implementation for Vero
ii  vero364-headers-4.9.113-18-osmc:arm64 18                                  arm64        Header files related to Linux kernel, specifically,
ii  vero364-image-4.9.113-18-osmc:arm64   18                                  arm64        Linux kernel binary image for version 4.9.113-18-osmc
ii  vero364-kernel-osmc:arm64             3.9.173                             arm64        Kernel meta package bringing in the latest OSMC kernel for this device
ii  wireless-firmware-osmc                1.1.5                               all          Wireless firmware (proprietary) for OSMC



So seeing as the video driver is built into the kernel how did they get mismatched ?

Thoughts ?

**Comment by develroo** [comment]
Oh? How did it not do that then with a full-upgrade ? How do I add that manually? Hmmm

**Comment by samnazarko** [comment]
Re-read the 4.9 test thread. It sounds like you haven’t updated the repository properly.

On 21 Oct 2020, at 14:29, develroo <notifications@github.com> wrote:

﻿

Oh? How did it not do that then with a full-upgrade ? How do I add that manually? Hmmm

**Comment by develroo** [comment]
ok seems adding 

`deb http://apt.osmc.tv videoimprovevero49 main` to sources.list 

seemed to have sorted it. Thanks!
