### ISSUE TITLE
armv7-bluez-osmc conflicts with (stock Debian?) bluez

### ISSUE THREAD

**Issue by acli** [osmc/osmc#589]
In the latest image (OSMC_TGT_rbp2_20201019.img.gz), trying to install pulseaudio-module-bluetooth results in what looks like the stock Debian bluez being installed, but the stock bluez conflicts with osmc’s own armv7-bluez-osmc package.

    ...
    Unpacking bluez (5.50-1.2~deb10u1) ...
    dpkg: error processing archive /var/cache/apt/archives/bluez_5.50-1.2~deb10u1_armhf.deb (--unpack):
     trying to overwrite '/etc/dbus-1/system.d/bluetooth.conf', which is also in package armv7-bluez-osmc 5.43-4
    dpkg-deb: error: paste subprocess was killed by signal (Broken pipe)
    ...

**Comment by DBMandrake** [comment]
You can't install the standard Debian bluez package on osmc as armv7-bluez-osmc will conflict with it. This is because it provides a custom built version of bluez using many of the same file paths.

**Comment by samnazarko** [comment]
We should Provides: the bluez package though (to my recollection).

**Comment by DBMandrake** [comment]
armv7-bluez-osmc doesn't currently use "Provides" as far as I can see.

Provides and Conflicts declarations could be added but for versioned dependency checks to works the provide would need a version number as well:

https://www.debian.org/doc/debian-policy/ch-relationships.html#virtual-packages-provides

I seem to recall we've run into problems with this in the past and this may be why this package doesn't already use provides. At the least any change like this would need to be thoroughly tested.

**Comment by samnazarko** [comment]
We had the transitional package when we had to introduce a specific BlueZ when Pi 3 came out, remember?

We bumped it so high it could never be superseded by Debian.

I can add a Provides: directive which should solve the problem

On 19 Dec 2020, at 23:39, Simon Byrnand <notifications@github.com> wrote:

﻿

armv7-bluez-osmc doesn't currently use "Provides" as far as I can see.

Provides and Conflicts declarations could be added but for versioned dependency checks to works the provide would need a version number as well:

https://www.debian.org/doc/debian-policy/ch-relationships.html#virtual-packages-provides

I seem to recall we've run into problems with this in the past and this may be why this package doesn't already use provides. At the least any change like this would need to be thoroughly tested.

**Comment by samnazarko** [comment]
Thanks for the report.

This issue should now be resolved in release.

Since early 2016, when the Raspberry Pi 3 was introduced with Bluetooth support, we've maintained our own BlueZ packages. So that users would smoothly transition from the Debian provided package to our package without file conflicts, we introduced a dummy package. This package satisfies any dependencies on bluez but allows us to package our bluez-osmc which has specific patches to support hardware (such as the Pi 3 Bluetooth module). 

We removed this package with the introduction of Debian Stretch, only to reinstate it later in a1090c173d256c73c067bbd1f20ff3a2c4cf6ea7 to satisfy dependencies mandated by pulseaudio-module-bluetooth.

I don't believe that this dependency is versioned, and IIRC, Buster's apt/dpkg implementations should now allow us to provide even for versioned dependencies, but to play it safe, we'll keep the bluez-osmc transitional package in release. This was planned to be released in Buster for release, but the package version was not bumped, so this was not included.

The issue should now be solved and you should be able to bring your system to a working state with the following commands:

```
apt-get update
apt-get -f install
```

I would appreciate it if you could let us know how this goes.

**Comment by acli** [comment]
The fix worked. Thank you

**Comment by samnazarko** [comment]
Thanks for confirming this.
