### ISSUE TITLE
Settings aren't stored on Raspberry Pi 2

### ISSUE THREAD

**Issue by IeP4nieF** [osmc/osmc#593]
Hi,

for me settings (most of the time) aren't stored, after changing them in the kodi gui. For Example the setting lookandfeel.skin. After changing the skin in the kodi-gui and leaving settings in kodi (returning to the main menu), the new setting isn't stored in guisettings.xml. So after a reboot, the old skin is used.

There seems to be no problem with the SD-Card. I checked with another SD-Card an the SD-Cards are both mount rw. With an editor I can change for example guisettings.xml. So there shouldn't be problemes related to the SD-Card.

I also don't know whether this is a Kodi or osmc bug (or a bug at all ;-) ). My vero 4k+ runs fine and I can change the gui on this devices. Because of this I guess, that it is a bug in osmc and not kodi. But I might be wrong.

I'm running osmc 2020.11-1.

best regards and keep up the good work!

**Comment by samnazarko** [comment]
Please start a forum post, this is for confirmed bugs only

Sam

On 13 Jan 2021, at 18:01, IeP4nieF <notifications@github.com> wrote:

﻿

Hi,

for me settings (most of the time) aren't stored, after changing them in the kodi gui. For Example the setting lookandfeel.skin. After changing the skin in the kodi-gui and leaving settings in kodi (returning to the main menu), the new setting isn't stored in guisettings.xml. So after a reboot, the old skin is used.

There seems to be no problem with the SD-Card. I checked with another SD-Card an the SD-Cards are both mount rw. With an editor I can change for example guisettings.xml. So there shouldn't be problemes related to the SD-Card.

I also don't know whether this is a Kodi or osmc bug (or a bug at all ;-) ). My vero 4k+ runs fine and I can change the gui on this devices. Because of this I guess, that it is a bug in osmc and not kodi. But I might be wrong.

I'm running osmc 2020.11-1.

best regards and keep up the good work!
