### ISSUE TITLE
Remote Control: igorplugusb not working on rbp2 since recent releases

### ISSUE THREAD

**Issue by tontaub0r** [osmc/osmc#675]
Hi,
on rbp2 my remote control doesn't work anymore since 2021.11-2.
I have found out, that the according kernel module isn't included anymore.

After building the kernel-osmc package on a local system with the reactivated module it works again as expected.
Please reactivate it in the code base again:
https://github.com/osmc/osmc/blob/master/package/kernel-osmc/patches/rbp2-000-add-kernel-config.patch

line 3561: +# CONFIG_IR_IGORPLUGUSB is not set

should be +CONFIG_IR_IGORPLUGUSB=m

Thanks,
Peter

**Comment by samnazarko** [comment]
I'm happy to accept a PR for this.

Please also update Pi 4 kernel config.

**Comment by tontaub0r** [comment]
Thanks

**Comment by samnazarko** [comment]
I'd appreciate it if you could test this and provide feedback before we potentially release this as an update to other users. To test this update:

1. [Login via the command line](https://osmc.tv/wiki/general/accessing-the-command-line/)
2. Run the following command to add the staging repository:
```echo 'deb http://apt.osmc.tv buster-devel main' | sudo tee /etc/apt/sources.list.d/osmc-devel.list```
3. Run the following commands to update: ```sudo apt-get update && sudo apt-get dist-upgrade && reboot```
4. Your system should have have received the update. 

Please see if the issue is resolved.

I also recommend you remove ```/etc/apt/sources.list.d/osmc-devel.list``` after updating. 

I'd also recommend you deactivate the staging repository. You can do so with the following command:
```sudo rm /etc/apt/sources.list.d/osmc-devel.list```. 

Please note that we will automatically disable this update channel after 14 days on your device in case you forget to do so to ensure that your system reverts to the stable update channel.

**Comment by tontaub0r** [comment]
Hi Sam, 
I have performed your steps and the test was positive. My remote control works again with the buster-devel kernel. 
The short smoke test of further regression bugs didn't reveal any other bugs.
Cheers,
Peter
