### ISSUE TITLE
Why is OSMC using customized network start script with connman?

### ISSUE THREAD

**Issue by cmonty14** [osmc/osmc#717]
Hi,

when I was investigating issue #716 I came across this:
connman.service is executing a customized network start script
```
osmc@osmc:~$ sudo systemctl cat connman.service
# /lib/systemd/system/connman.service
[Unit]
Description=Connman connection service
After=dbus.service network-pre.target wpa_supplicant.service
Wants=network.target remote-fs-pre.target
Before=remote-fs-pre.target network.target

[Service]
Type=dbus
BusName=net.connman
EnvironmentFile=-/etc/connman.prefs
Restart=always
RestartSec=5
ExecStart = /usr/bin/start-network
ExecStopPost = /bin/sleep 2
StandardOutput=null

[Install]
WantedBy=multi-user.target

```

Why don't you use the service file delivered by package *connman_1.36-2.2+deb11u1_armhf.deb*?
```osmc@osmc:~$ cat /tmp/connman/lib/systemd/system/connman.service                 
[Unit]
Description=Connection service
DefaultDependencies=false
Conflicts=shutdown.target
RequiresMountsFor=/var/lib/connman
After=dbus.service network-pre.target systemd-sysusers.service
Before=network.target multi-user.target shutdown.target
Wants=network.target

[Service]
Type=dbus
BusName=net.connman
Restart=on-failure
ExecStart=/usr/sbin/connmand -n
StandardOutput=null
CapabilityBoundingSet=CAP_NET_ADMIN CAP_NET_BIND_SERVICE CAP_NET_RAW CAP_SYS_TIME CAP_SYS_MODULE
ProtectHome=true
ProtectSystem=full

[Install]
WantedBy=multi-user.target
```

Regards
Thomas

**Comment by samnazarko** [comment]
That’s because we ship connman downstream.
GitHub is for confirmed bug reports only, so I suggest you take things to the forums.

On 27 Nov 2022, at 08:34, Thomas ***@***.***> wrote:

﻿

Hi,

when I was investigating issue #716<https://github.com/osmc/osmc/issues/716> I came across this:
connman.service is executing a customized network start script

***@***.***:~$ sudo systemctl cat connman.service
# /lib/systemd/system/connman.service
[Unit]
Description=Connman connection service
After=dbus.service network-pre.target wpa_supplicant.service
Wants=network.target remote-fs-pre.target
Before=remote-fs-pre.target network.target

[Service]
Type=dbus
BusName=net.connman
EnvironmentFile=-/etc/connman.prefs
Restart=always
RestartSec=5
ExecStart = /usr/bin/start-network
ExecStopPost = /bin/sleep 2
StandardOutput=null

[Install]
WantedBy=multi-user.target



Why don't you use the service file delivered by package connman_1.36-2.2+deb11u1_armhf.deb?

[Unit]
Description=Connection service
DefaultDependencies=false
Conflicts=shutdown.target
RequiresMountsFor=/var/lib/connman
After=dbus.service network-pre.target systemd-sysusers.service
Before=network.target multi-user.target shutdown.target
Wants=network.target

[Service]
Type=dbus
BusName=net.connman
Restart=on-failure
ExecStart=/usr/sbin/connmand -n
StandardOutput=null
CapabilityBoundingSet=CAP_NET_ADMIN CAP_NET_BIND_SERVICE CAP_NET_RAW CAP_SYS_TIME CAP_SYS_MODULE
ProtectHome=true
ProtectSystem=full

[Install]
WantedBy=multi-user.target


Regards
Thomas
