### ISSUE TITLE
fail to build install/target on Ubuntu 22.04 and Debian 12

### ISSUE THREAD

**Issue by TermeHansen** [osmc/osmc#742]
I fail to build installer/target on both my Ubuntu 22.04 server and a Debian 12 (bookworm) server I have, the error comes in the buildroot part:

```
../../gcc/reload1.c:89:24: error: use of an operand of type ‘bool’ in ‘operator++’ is forbidden in C++17
   89 |   (this_target_reload->x_spill_indirect_levels)
      |   ~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~

```
I guess it is because both distros rely on a "to-new" cc version or?

**Comment by samnazarko** [comment]
That’s expected, will clarify shortly.

On 29 Aug 2023, at 22:13, Rasmus Lundsgaard ***@***.***> wrote:

﻿

I fail to build installer/target on both my Ubuntu 22.04 server and a Debian 12 (bookworm) server I have, the error comes in the buildroot part:

../../gcc/reload1.c:89:24: error: use of an operand of type ‘bool’ in ‘operator++’ is forbidden in C++17
89 | (this_target_reload->x_spill_indirect_levels)
| ~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~

I guess it is because both distros rely on a "to-new" cc version or?

**Comment by samnazarko** [comment]
The installer is quite old (based on Buildroot 2014.05) and uses GCC 4.9. We are using such an old version because our installer runs on Qt 4.x. I plan to update this to Qt5.x in the future, but we don't have sufficient resources at the moment. As a stop gap, the plan is to move to the last version of Buildroot (2018.11) which supports Qt 4.x but also has a newer version of GCC.

This should keep us going for a bit longer. It is also a necessity as RPi's next kernel will be Linux 6.1, and we want to keep the installers in sync with the kernel running on the target.

As such, I'm currently working on a new branch ```targetinsttupdate```. 
Please be aware that I am force pushing it as I make improvements.

This should build under Ubuntu 22.04, but I'm having some issues getting the actual installer up and running which I'm looking in to as we speak. I can keep you updated, but I'd recommend you check out this branch and at least verify that the installer builds as expected for you

I hope this all helps. I've wanted to support full USB booting before, but have not had the time to work on it. I'm glad to help anyone that wants to implement it.

**Comment by samnazarko** [comment]
Great, I’ve verified and it’s working on RBP4 (run time tested).

 So will verify Vero targets and then make this the default installer environment.

On 31 Aug 2023, at 17:45, Rasmus Lundsgaard ***@***.***> wrote:

﻿

Build completed
for rbp4 on Ubuntu 22.04 server...

**Comment by TermeHansen** [comment]
Not to start a big discussion, but my eye just caught a lot of "hello" stuff getting compiled and installed?!? it looks like it is the example in:

`host/share/doc/gettext/examples/hello-c
`
I guess it doesn't matter, as it works :smile_cat:

**Comment by samnazarko** [comment]
That will be coming from gettext.

I think those examples are built but don't believe they're installed on the target.

________________________________

**Comment by samnazarko** [comment]
As this now builds, I will mark this issue as closed.
