### ISSUE TITLE
Music playing is killed when tv is off, cec-vc4: transmit timed out

### ISSUE THREAD

**Issue by glormph** [osmc/osmc#778]
I have some issue on a raspberry pi 4 (Debian bullseye, latest OSMC, 2024.10.1 but problem occurred in earlier versions too), when playing music, with the tv turned off, or not connected (HDMI). Music randomly stops playing after maybe 30 seconds. The remote also disconnects at that point, but an SSH session stays connected. When running,  `dmesg | tail` shows continuous messages of `cec-vc4: message 10 timed out`, but when the music stops, it will print `cec-vc4: transmit timed out`. After a short interruption the remote can reconnect and music can be played.

When the tv is connected and on when the system starts/reboots, none of the `cec-vc4` messages are in the dmesg. When turning the tv off then, it keeps working and no messages appear.

I'm not very knowledgeable of audio/video systems but have understood CEC has something to do with controlling the tv over HDMI, so I'm guessing it's trying to communicate with the tv but it doesnt work somehow. Also, I'm not sure if I have put this issue in the correct repo or that the problem is not OSMC's, so apologies if it's wrongly placed.

**Comment by samnazarko** [comment]
Please start a forum post.

On 8 Dec 2024, at 15:19, Jorrit Boekel ***@***.***> wrote:

﻿

I have some issue on a raspberry pi 4 (Debian bullseye, latest OSMC, 2024.10.1 but problem occurred in earlier versions too), when playing music, with the tv turned off, or not connected (HDMI). Music randomly stops playing after maybe 30 seconds. The remote also disconnects at that point, but an SSH session stays connected. When running, dmesg | tail shows continuous messages of cec-vc4: message 10 timed out, but when the music stops, it will print cec-vc4: transmit timed out. After a short interruption the remote can reconnect and music can be played.

When the tv is connected and on when the system starts/reboots, none of the cec-vc4 messages are in the dmesg. When turning the tv off then, it keeps working and no messages appear.

I'm not very knowledgeable of audio/video systems but have understood CEC has something to do with controlling the tv over HDMI, so I'm guessing it's trying to communicate with the tv but it doesnt work somehow. Also, I'm not sure if I have put this issue in the correct repo or that the problem is not OSMC's, so apologies if it's wrongly placed.
